- name: Update web servers
  hosts: amazon-clients
  remote_user: root
  vars_files:
  - variables.yml 

  tasks:
  - name: Update all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
  - name: Install apache
    ansible.builtin.yum:
      name: '{{amazon-package}}'
      state: present
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: '{{amazon-package}}'
      state: started
  - name: Start on boot enabled
    ansible.builtin.service:
      name: '{{amazon-package}}'
      enabled: true
  - name: Copy index.html file to target servers
    ansible.builtin.copy:
      src: /home/ubuntu/index.html
      dest: /var/www/html/
    notify:
    - restart httpd

  handlers:
  - name: restart httpd
    ansible.builtin.service:
      name: '{{amazon-package}}'
      state: restarted
